#!/bin/bash

set -e

if [[ $# != 3 ]]; then
	echo "Usage: ngen [number of nodes] [destination] [IP BASE (ex: 172.77.5.)]"
	exit 0
fi

N=${1}
DEST=${2}
IPBASE=${3}

for i in $(seq 1 $N) 
do
	dest=$DEST/node$i
	mkdir -p $dest
	babble keygen | sed -n -e "2 w $dest/pub" -e "4,+4 w $dest/priv_key.pem"
	echo $IPBASE$i > $dest/addr
done

PFILE=$DEST/peers.json
echo "[" > $PFILE 
for i in $(seq 1 $N)
do
	printf "\t{\n" >> $PFILE
	printf "\t\t\"NetAddr\":\"$(cat $DEST/node$i/addr)\",\n" >> $PFILE
	printf "\t\t\"PubKeyHex\":\"$(cat $DEST/node$i/pub)\"\n" >> $PFILE
	printf "\t},\n" >> $PFILE

done
echo "]" >> $PFILE

for i in $(seq 1 $N) 
do
	dest=$DEST/node$i
	cp $DEST/peers.json $dest/
done

