#!/bin/bash

set -eux

MPWD=$(pwd)

docker network create \
  --driver=bridge \
  --subnet=172.77.0.0/16 \
  --ip-range=172.77.5.0/24 \
  --gateway=172.77.5.254 \
  babblenet

for i in $(seq 1 4)
do
    docker create --name=node$i --net=babblenet --ip=172.77.5.$i babble run \
    --tcp_timeout=4000 \
    --heartbeat=75 \
    --node_addr="172.77.5.$i:1337" \
    --proxy_addr="172.77.5.$i:1338" \
    --client_addr="172.77.5.1$i:1339" 
    docker cp $MPWD/node$i node$i:/.babble
    docker start node$i

    docker run -d --name=client$i --net=babblenet --ip=172.77.5.1$i -it dummy \
    --name="client $i" \
    --client_addr="172.77.5.1$i:1339" \
    --proxy_addr="172.77.5.$i:1338" \
    --log_level="info"  
done