#!/bin/bash

CA_KEY=ca.key
CA_CRT=ca.crt

# secp256p1
CURVE=${CURVE:-prime256v1}
HASH=${HASH:-SHA256}
DAYS=${DAYS:-30}

# Create the self-signed key pair for the CA
CA_SUBJECT='/C=UK/ST=Sealand/L=London/O=MosaicNetworks/OU=IT/CN=babble.net'

# secp256p1
openssl ecparam -genkey -name $CURVE -out $CA_KEY
# CSR
openssl req -x509 -new -$HASH -nodes -key $CA_KEY -days $DAYS -out $CA_CRT -subj "$CA_SUBJECT"

# Generate certificates and sign with the CA's key:
for n in `seq 1 ${1:-0}`; do
    node=node$n
    echo "generating key and certificate for node $node"
    node_key=$node.key
    node_csr=$node.csr
    node_crt=$node.crt
    node_subject="/C=UK/ST=Sealand/L=London/O=MosaicNetworks/OU=IT/CN=$node.babble.net"
    openssl ecparam -genkey -name $CURVE -out $node_key
    openssl req -new -$HASH -key $node_key -nodes -out $node_csr -subj $node_subject
    openssl x509 -req -$HASH -days $DAYS \
                      -CA $CA_CRT -CAkey $CA_KEY -CAcreateserial \
                      -in $node_csr -out $node_crt
    rm -f $node_csr
done

