#!/bin/bash

export DAYS=3650
DST=../net/testdata
./rootca 2
mv ca.{crt,key} "$DST"
for i in 1 2; do
  for t in key crt; do
    mv node$i.$t "$DST/signed$i.$t"
  done
done

# Create a new CA and certificate to use as `unsigned`
./rootca 1
mv node1.key "$DST/unsigned.key"
mv node1.crt "$DST/unsigned.crt"

rm -f ca.{key,crt,srl}
